#!/usr/bin/env Rscript
# ==============================================================================
# diff-models.r — what changed between the 2025 and the 2026 Vensim model
#
#   Rscript tool/diff-models.r          # writes DIFF-2025-2026.md
#
# The comparison in README section 2 was done once, by hand, and could not be
# replayed. Phase 2 needs it as a tool: before retranslating an equation, read
# what the 2026 model did to it rather than guessing.
#
# Three questions, and the third is the one that costs time if skipped:
#
#   which variables are gone      the R translating them may be dead code
#   which are new                 they have to be written from nothing
#   which KEPT THEIR NAME but had their equation changed
#
# The last is the dangerous one. A variable whose name is unchanged looks
# translated; if its equation moved underneath, the R is quietly wrong and
# nothing says so.
# ==============================================================================

suppressPackageStartupMessages(library(here))
source(here::here("src", "paths.r"))

F25 <- file.path(DIR_DOCS, "EUROGREEN", "vensimModel_noDelete.txt")
F26 <- file.path(PROJECT_ROOT, "vensim_model_2026.txt")
OUT <- file.path(PROJECT_ROOT, "DIFF-2025-2026.md")

## Every equation of a model: name -> its body, normalised.
##
## An equation runs from a name at the start of a line up to the closing `|`.
## Normalising collapses whitespace and drops the units and comment trailer, so
## that a reflowed line or an edited comment does not read as a changed equation.
equations <- function(path) {
  raw <- readLines(path, warn = FALSE)
  raw <- sub("\\\\\\s*$", "", raw)
  txt <- paste(raw, collapse = "\n")

  starts <- grep("^[A-Za-z\"][^=\n]*=", strsplit(txt, "\n")[[1]])
  lines  <- strsplit(txt, "\n")[[1]]
  ends   <- c(starts[-1] - 1, length(lines))

  out <- list()
  for (k in seq_along(starts)) {
    block <- paste(lines[starts[k]:ends[k]], collapse = " ")
    name  <- sub("^([A-Za-z\"][^=\\[]*?)\\s*(?:\\[[^]]*\\])?\\s*=.*$", "\\1", block)
    name  <- trimws(gsub('"', "", name))
    body  <- sub("^[^=]*=", "", block)
    body  <- sub("~.*$", "", body)                    # units and comment: not the equation
    body  <- trimws(gsub("[[:space:]]+", " ", body))
    if (nzchar(name) && is.null(out[[name]])) out[[name]] <- list(body = body, line = starts[k])
  }
  out
}

e25 <- equations(F25); e26 <- equations(F26)
n25 <- names(e25);     n26 <- names(e26)

gone    <- sort(setdiff(n25, n26))
added   <- sort(setdiff(n26, n25))
common  <- sort(intersect(n25, n26))
changed <- Filter(function(n) e25[[n]]$body != e26[[n]]$body, common)
same    <- setdiff(common, changed)

## A switch flipped from 1 to 0 is not the same event as a formula rewritten.
is_number <- function(x) grepl("^-?[0-9.eE+-]+$", trimws(x))
retuned <- Filter(function(n) is_number(e25[[n]]$body) && is_number(e26[[n]]$body), changed)
rebuilt <- setdiff(changed, retuned)

## Which of these does the R already translate? Those are the ones where an
## existing translation looks current and is not.
claimed <- character()
map <- file.path(PROJECT_ROOT, "MAPPING.md")
if (file.exists(map)) {
  ml <- readLines(map, warn = FALSE)
  det <- cumsum(grepl("^<details>", ml)) > cumsum(grepl("^</details>", ml))
  rows <- ml[!det & grepl("^\\|\\s*`", ml)]
  claimed <- unique(unlist(lapply(rows, function(r) {
    v <- sub("^\\|[^|]*\\|[^|]*\\|([^|]*)\\|.*$", "\\1", r)
    v <- gsub("~~[^~]*~~", "", v); v <- sub(".*\u2192", "", v)
    gsub("`", "", regmatches(v, gregexpr("`[^`]+`", v))[[1]])
  })))
}
at_risk <- intersect(rebuilt, claimed)

## A rename usually leaves the new name containing the old one.
suggest <- function(lost) {
  c <- added[grepl(lost, added, fixed = TRUE) | startsWith(added, paste0(lost, " "))]
  if (length(c)) paste(sprintf("`%s`", head(c, 3)), collapse = ", ") else ""
}

esc <- function(s) gsub("\\|", "\\\\|", s)
trunc <- function(s, n = 150) if (nchar(s) > n) paste0(substr(s, 1, n), " ...") else s

w <- c()
add <- function(...) w <<- c(w, paste0(...))

add("# Vensim 2025 → 2026\n")
add("Generated by `Rscript tool/diff-models.r`. Regenerate it rather than editing it.\n")
add("Equations are compared after collapsing whitespace and dropping the units and")
add("comment trailer, so a reflowed line or an edited comment does not show up as a")
add("changed equation.\n")
add("| | |")
add("|---|---|")
add(sprintf("| equations in 2025 | %d |", length(n25)))
add(sprintf("| equations in 2026 | %d |", length(n26)))
add(sprintf("| removed | %d |", length(gone)))
add(sprintf("| added | %d |", length(added)))
add(sprintf("| kept, equation unchanged | %d |", length(same)))
add(sprintf("| kept, only a constant changed | %d |", length(retuned)))
add(sprintf("| **kept, equation rewritten** | **%d** |", length(rebuilt)))
add(sprintf("| **of those, already translated in R** | **%d** |", length(at_risk)))
add("")
add("---\n")
add("## Already translated, and the equation changed\n")
add("**Start here.** Each of these has a row in `MAPPING.md`, so the R looks")
add("current — and the Vensim equation moved underneath it. Nothing in the code")
add("says so, and the name is unchanged, so nothing will.\n")
if (!length(at_risk)) add("None.\n") else {
  add("| Vensim | 2025 | 2026 | line |")
  add("|---|---|---|---|")
  for (n in sort(at_risk)) {
    add(sprintf("| `%s` | `%s` | `%s` | %d |", esc(n),
                esc(trunc(e25[[n]]$body)), esc(trunc(e26[[n]]$body)), e26[[n]]$line))
  }
  add("")
}
add("---\n")
add("## Same name, equation rewritten\n")
add("The rest of them: not translated yet, so nothing is wrong today, but the 2025")
add("equation is no longer the one to translate.\n")
add("<details><summary>Show the list</summary>\n")
add("| Vensim | 2025 | 2026 | line |")
add("|---|---|---|---|")
for (n in sort(setdiff(rebuilt, at_risk))) {
  add(sprintf("| `%s` | `%s` | `%s` | %d |", esc(n),
              esc(trunc(e25[[n]]$body)), esc(trunc(e26[[n]]$body)), e26[[n]]$line))
}
add("\n</details>\n")
add("---\n")
add("## Same name, only a constant changed\n")
add("A switch flipped, a parameter retuned. Cheap to check, easy to miss.\n")
add("| Vensim | 2025 | 2026 |")
add("|---|---|---|")
for (n in sort(retuned)) {
  add(sprintf("| `%s` | `%s` | `%s` |", esc(n), esc(e25[[n]]$body), esc(e26[[n]]$body)))
}
add("")
add("---\n")
add("## Removed in 2026\n")
add("An R function translating one of these is translating something that no longer")
add("exists. Some are renames rather than removals; the last column suggests a")
add("candidate when the new name contains the old one.\n")
add("<details><summary>Show the list</summary>\n")
add("| Vensim 2025 | possible new name |")
add("|---|---|")
for (n in gone) add(sprintf("| `%s` | %s |", esc(n), esc(suggest(n))))
add("\n</details>\n")
add("---\n")
add("## Added in 2026\n")
add("Nothing in the R translates these yet.\n")
add("<details><summary>Show the list</summary>\n")
add("| Vensim 2026 | line |")
add("|---|---|")
for (n in added) add(sprintf("| `%s` | %d |", esc(n), e26[[n]]$line))
add("\n</details>")

writeLines(w, OUT)
cat(sprintf(paste0("DIFF-2025-2026.md\n",
  "  removed %d | added %d | untouched %d\n",
  "  same name, constant changed %d | equation rewritten %d\n",
  "  of the rewritten, already translated in R: %d  <- start here\n"),
  length(gone), length(added), length(same), length(retuned), length(rebuilt), length(at_risk)))
