---
jupyter:
  kernelspec:
    display_name: R 4.5 (renv)
    language: R
    name: r-4.5-renv
---

```{r}
#| jupyter: {source_hidden: true}
# pkg
options(jupyter.rich_display = TRUE) 
suppressPackageStartupMessages(
    {
        library(here) 
        library(shiny) 
        library(bslib) #  modern UI toolkit for Shiny
        library(dplyr)
        library(data.table)
        library(htmlwidgets)
        library(htmltools)
        library(DiagrammeR) #to make graph
        library(RColorBrewer)
        library(visNetwork) #to make graph
        
    }
)
output_path <- DIR_OUTPUT
load(file.path(output_path,"model_only.RData"))
     
```

```{r}
#| jupyter: {source_hidden: true}
# constructing node and edge df
all_vars_in_d <- as.character(levels(unique(d$Name)))
all_vars <- all_vars_in_d
edges_list <- list()
for (var in all_vars) {  
  obj <- gd(var, 2010) 
  deps <- attr(obj, "deps")

    for (dep in deps) {
      edges_list <- append(edges_list, list(c(dep, var)))
    }
}

## Transformer en data.frame pour DiagrammeR
edges_df <- do.call(rbind, edges_list)
colnames(edges_df) <- c("from", "to")
edges_df <- as.data.frame(edges_df, stringsAsFactors = FALSE)

# Adding missing nodes from edges df to nodes df (ie lagged variables)
missing_from <- edges_df$from[!edges_df$from %in% all_vars]
all_vars <- unique(c(missing_from, all_vars))

# get rid of structurel element (t, gender, and the like) that are in toKeep
edges_df <- edges_df[-which(edges_df$from %in% c(toKeep, "t")),]
all_vars <- all_vars[-which(all_vars %in% c(toKeep, "t"))]
# add columns type to nodes_df with lag as defautl value (it will get overriden afterwards
nodes_df <- data.frame(id = 1:length(all_vars), label = all_vars)
nodes_df$type <- "lag"

# Assurer que les `from` et `to` sont bien des caractères
edges_df$from <- as.character(edges_df$from)
edges_df$to <- as.character(edges_df$to)

edges_df$from_name <- as.character(edges_df$from)
edges_df$to_name <- as.character(edges_df$to)

# Associer chaque `from` et `to` avec l'index correspondant dans nodes_df
edges_df$from <- match(edges_df$from, nodes_df$label)
edges_df$to <- match(edges_df$to, nodes_df$label)

# add module to nodes_df$type
for(var in all_vars_in_d){
    mod_obj <- d[Name == var & Period == t, Module]
    nodes_df$type[which(nodes_df$label==var)] <- as.character(mod_obj)
}

    # Créer une palette de couleurs pour chaque type (niveau)
unique_types <- unique(nodes_df$type)
colors <- RColorBrewer::brewer.pal(length(unique_types), "Set3")  # Choisir une palette
names(colors) <- unique_types  # Associer chaque couleur à un type

# https://rich-iannone.github.io/DiagrammeR/reference/node_aes.html
# Ajouter une colonne de couleur à nodes_df en fonction du type
nodes_df$fillcolor <- colors[nodes_df$type]
nodes_df$shape <- "circle" # circle, rectangle, triangle, plaintext, square, and polygon.
nodes_df$shape[which(nodes_df$type!="lag")]  <- "rectangle"
nodes_df$fillcolor[which(nodes_df$type=="lag")]  <- "#F0F0F0"

# add description field to nodes_df
d_firsPeriod <- d[Period==gp("startYear"),]
nodes_df$description <- d_firsPeriod[nodes_df, on = .(Name = label), x.Description]
#nodes_df

# Create from_type and to_type dans edges_df
edges_df <- edges_df %>%
  left_join(nodes_df %>% select(id, type), by = c("from" = "id")) %>%
  rename(from_type = type)

edges_df <- edges_df %>%
  left_join(nodes_df %>% select(id, type), by = c("to" = "id")) %>%
  rename(to_type = type)
```

```{r}
#| jupyter: {source_hidden: true}
# Export edge and node df to app folder 

app_path <- file.path(DIR_APP, "graph")
graph_obj <- list()
graph_obj[["edges"]] <- edges_df
graph_obj[["nodes"]] <- nodes_df


save(graph_obj, file = file.path(app_path, "graph_obj.RData"))
```

```{r}
# Run app 

graph_app_path <- file.path(DIR_APP, "graph")
runApp(paste0(graph_app_path, "/app.r")) 
```

```{r}
# Exemple further
#runApp(system.file("shiny", package = "visNetwork"), display.mode="showcase")
```

```{r}

```

