---
jupyter:
  kernelspec:
    display_name: R 4.5 (renv)
    language: R
    name: r-4.5-renv
---

```{r}
#| jupyter: {source_hidden: true}
# Pkg
options(jupyter.rich_display = TRUE) 

suppressPackageStartupMessages(
    {
        library(here) 
        library(shiny) 
        library(bslib) #  modern UI toolkit for Shiny
        library(dplyr)
        library(data.table)
        library(htmlwidgets)
        library(htmltools)
        library(DiagrammeR) #to make graph
        library(visNetwork) #to make graph
        
    }
)

output_path <- DIR_OUTPUT

load(paste0(output_path, "/model_only.RData"))
```

```{r}
# Prepare, create and save graphs in RData
options(jupyter.rich_display = FALSE)

## TODO VIZ ##

# convergence still appears in the graph 
# style : The node line style. The style types that can be used are: filled, invisible, diagonals, rounded, dashed, dotted, solid, and bold.
## We will use style to depict period connectors : on les fixera tous à x = 0 et y variable en fonction de leur position dans la chronologie
# penwidth : we will use this to depict module connectors et ces derniers seront fixés à une position de y (en ordonnées les module) et de x en fonction du temps


# Oriented graph with variable.namesles in d 

all_vars_in_d <- as.character(levels(unique(d$Name)))
all_vars <- all_vars_in_d
edges_list <- list()
for (var in all_vars) {  
  obj <- gd(var, 2010) 
  deps <- attr(obj, "deps")

    for (dep in deps) {
      edges_list <- append(edges_list, list(c(dep, var)))
    }
}


## Transformer en data.frame pour DiagrammeR
edges_df <- do.call(rbind, edges_list)
colnames(edges_df) <- c("from", "to")
edges_df <- as.data.frame(edges_df, stringsAsFactors = FALSE)

# Vérifier quelles valeurs de 'from' et 'to' ne sont pas dans 'nodes_df$label'
missing_from <- edges_df$from[!edges_df$from %in% all_vars]
all_vars <- unique(c(missing_from, all_vars))
# get rid of structurel element (t, gender, and the like) that are in toKeep
edges_df <- edges_df[-which(edges_df$from %in% c(toKeep, "t")),]
#edges_df <- edges_df[-which(edges_df$to %in% c(toKeep, "t")),]
all_vars <- all_vars[-which(all_vars %in% c(toKeep, "t"))]

# add columns type to nodes_df with lag as defautl value (it will get overriden afterwards
nodes_df <- data.frame(id = 1:length(all_vars), label = all_vars)
nodes_df$type <- "lag"

# Assurer que les `from` et `to` sont bien des caractères
edges_df$from <- as.character(edges_df$from)
edges_df$to <- as.character(edges_df$to)

edges_df$from_name <- as.character(edges_df$from)
edges_df$to_name <- as.character(edges_df$to)

# Associer chaque `from` et `to` avec l'index correspondant dans nodes_df
edges_df$from <- match(edges_df$from, nodes_df$label)
edges_df$to <- match(edges_df$to, nodes_df$label)

# add module to nodes_df$type
for(var in all_vars_in_d){
    mod_obj <- d[Name == var & Period == t, Module]
    nodes_df$type[which(nodes_df$label==var)] <- as.character(mod_obj)
}

    # Créer une palette de couleurs pour chaque type (niveau)
unique_types <- unique(nodes_df$type)
colors <- RColorBrewer::brewer.pal(length(unique_types), "Set3")  # Choisir une palette
names(colors) <- unique_types  # Associer chaque couleur à un type

# https://rich-iannone.github.io/DiagrammeR/reference/node_aes.html
# Ajouter une colonne de couleur à nodes_df en fonction du type
nodes_df$fillcolor <- colors[nodes_df$type]
nodes_df$shape <- "circle" # circle, rectangle, triangle, plaintext, square, and polygon.
nodes_df$shape[which(nodes_df$type!="lag")]  <- "rectangle"
nodes_df$fillcolor[which(nodes_df$type=="lag")]  <- "#F0F0F0"
#nodes_df

# Create from_type and to_type dans edges_df
edges_df <- edges_df %>%
  left_join(nodes_df %>% select(id, type), by = c("from" = "id")) %>%
  rename(from_type = type)

edges_df <- edges_df %>%
  left_join(nodes_df %>% select(id, type), by = c("to" = "id")) %>%
  rename(to_type = type)
# Set position :y l'eéchelle des modules, x l'échelle du "temps" -> THIS IS INEFFECTIVE FOR SOME REASON
#n_modules <- 1/(length(modules) - 1)
#coord_y <- seq(0, 1, n_modules)
#c <- 100
#n_lag <- length(which(nodes_df$type=="lag"))
#which_lag <- which(nodes_df$type=="lag")
#n_var <- nrow(nodes_df) - n_lag
#which_var <- which(nodes_df$type!="lag")
## X-axis
##nodes_df$x <- 1
##nodes_df$x[which_lag] <- runif(n_lag, 0, 0.05) * c
#nodes_df$x[which_var] <- runif(n_var, 0.95, 1) * c
##nodes_df <- nodes_df %>% filter(type=="lag") %>% mutate(x = runif(n_lag, 0, 0.25) *c)
#nodes_df <- nodes_df %>% filter(type!="lag") %>% mutate(x = runif(n_var,0.5, 1) *c)
#nodes_df$x <- runif(nrow(nodes_df)) 
#nodes_df$x[which(nodes_df$type=="lag")] <- nodes_df$x / 4
#nodes_df$x[which(nodes_df$type=="lag")]  <- .25 * c# lag are in the past
# Y-axis 
#nodes_df$y <- coord_y[match(nodes_df$type,modules)] * c
#nodes_df$y[which(is.na(nodes_df$y))] <- runif(is.na(nodes_df$y))

# Creating and exporting as html directed graphs
options(jupyter.rich_display = TRUE)
h <- 1400
w <- 2300

mods <- as.character(unique(nodes_df$type))
mods <- mods[-which(mods == "lag")]
n_graph <- length(mods) + 1
graphs <- vector("list", n_graph)
displays <- vector("list", n_graph)

# MAIN -------------------------------------------------------
graph <- create_graph(directed=TRUE) %>%
    add_nodes_from_table(
        table = nodes_df, 
        label_col = label, 
        type_col = type
      ) %>% 
    add_edges_from_table(
        table = edges_df, 
        from_col = from, 
        to_col = to, 
        from_to_map = id_external
      )%>%
    render_graph(layout = "nicely",  # nicely, circle, tree, kk, and fr.
              title=paste0("REWIND ",  "(", Sys.date(),")"),
              width=1500,
              height=1000,
               output="visNetwork"
              )

graph$sizingPolicy$defaultHeight <- h
graph$sizingPolicy$defaultWidth <- w

legend_items <- unique(nodes_df[, c("type", "fillcolor")])
legend_html <- tags$div(
  style = "display: flex; flex-wrap: wrap; gap: 15px; margin: 20px 0; justify-content: center;",
  lapply(1:nrow(legend_items), function(i) {
    tags$div(
      style = "display: flex; align-items: center; gap: 8px; text-align: center;",
      tags$div(style = paste0("width: 20px; height: 20px; background-color: ", legend_items$fillcolor[i], "; border: 1px solid #000;")),
      tags$span(legend_items$type[i])
    )
  })
)
display <- htmltools::tagList(
  tags$h1(
    paste0("REWIND (", Sys.Date(), ")"),
    style = "text-align: center;"
  ),
    legend_html,
    graph
  
) 


graphs[["main"]] <- graph
displays[["main"]] <-  display

#output_path <- here::DIR_OUTPUT
#graph_path <- here(output_path, "main_graph")
#htmltools::save_html(display, paste0(graph_path, ".html"))
#saveWidget(main_display, paste0(main_graph_path, ".html"), selfcontained=TRUE)

# MODULE -------------------------------------------------------
mods <- as.character(unique(nodes_df$type))
mods <- mods[-which(mods == "lag")]
for(mod in mods){
 # 1. Filtrer les arêtes du module
  edges_sub <- edges_df %>% 
        filter(from_type == mod | to_type == mod)
  
  # Sauter si aucun edge trouvé
  if (nrow(edges_sub) == 0) next
  
  # 2. Extraire les noms des objets (nœuds)
  obj_in_sub <- unique(c(edges_sub$from_name, edges_sub$to_name))
  
  # 3. Sous-ensemble de nœuds
  nodes_sub <- nodes_df %>% 
    filter(label %in% obj_in_sub)
  
  # 4. Créer le graphe
  graph <- create_graph(directed = TRUE) %>%
    add_nodes_from_table(
      table = nodes_sub, 
      label_col = label, 
      type_col = type
    ) %>%
    add_edges_from_table(
      table = edges_sub,
      from_col = from,
      to_col = to,
        from_to_map = id_external
    ) %>%
    render_graph(
      layout = "nicely",
      title = paste0("REWIND Module: ", mod, "(", Sys.date(),")"),
      width = 1500,
      height = 1000,
      output = "visNetwork"
    )

    graph$sizingPolicy$defaultHeight <- h
    graph$sizingPolicy$defaultWidth <- w

    legend_items <- unique(nodes_df[, c("type", "fillcolor")])
    legend_html <- tags$div(
      style = "display: flex; flex-wrap: wrap; gap: 15px; margin: 20px 0; justify-content: center;",
      lapply(1:nrow(legend_items), function(i) {
        tags$div(
          style = "display: flex; align-items: center; gap: 8px; text-align: center;",
          tags$div(style = paste0("width: 20px; height: 20px; background-color: ", legend_items$fillcolor[i], "; border: 1px solid #000;")),
          tags$span(legend_items$type[i])
        )
      })
    )
    
    display <- htmltools::tagList(
        tags$h1(
            paste0("REWIND: ", mod, " (", Sys.Date(), ")"),
            style = "text-align: center;"
        ),
            legend_html,

        graph
    ) 

    

    graphs[[mod]] <- graph    
    displays[[mod]] <-  display
    
#    output_path <- here::DIR_OUTPUT
 #   graph_path <- here(output_path, mod)
    #htmltools::save_html(display, paste0(graph_path, ".html"))
#saveWidget(display, paste0(graph_path, ".html"), selfcontained=TRUE)
}

# Save environment to write documentation 
file_path <- path_output("model_graph")
save.image(file = paste0(file_path, ".RData"))
```

```{r}
#| jupyter: {source_hidden: true}
# Run graph.r ShinyApp
#graph_app_path <- path_output("graph")
graph_app_path <- file.path(DIR_APP, "graph")
runApp(paste0(graph_app_path, "/app.r")) 

# Should also work 
#source(paste0(graphApp_path, "graphApp.r")) #App code
#shinyApp(ui = ui, server = server)
```

```{r}
#| jupyter: {source_hidden: true}
# Define UI for app that draws a histogram ----
ui <- page_sidebar(
    title = "REWIND module",
    sidebar = sidebar("Available graphs", 
                      position="right"
                     ),
    graphs[[mod]]
    
)

# Server 

# Define server logic ----
server <- function(input, output) {


}

# Run the app ----
shinyApp(ui = ui, server = server)

#shiny::runApp(system.file("shiny", package = "visNetwork"))
```

